### ISSUE TITLE
[RM Ch04] Define extensibility and scalability of profiles

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#175] opened 2019-08-07 05:07 UTC
This Issue captures a comment collected from Paris, entered against the original RM Chapter-4 Etherpad, for comment JB-2. Per initial triage, it applies to original Chapters 4.
- JB-2: Define extensibility and scalability of profiles

**Comment by rabi-abdel** [comment] 2019-10-01 20:15
More Text is needed to explain how instances can be extended with HW Accel, storage, etc.

**Comment by kedmison** [comment] 2020-04-29 14:17
Per RM meeting 2020-04-29, closing as duplicate of the following issues:
Extensions framework pull: #1354 
VNF backward evolution: #1008
VNF forward evolution: #1009

**Closed by kedmison** 2020-04-29 14:17 UTC
