### ISSUE TITLE
[RM Ch04] Naming Scheme Related Refinements

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#178] opened 2019-08-07 05:25 UTC
This Issue captures a comment collected from Paris, entered against the original RM Chapter-4 Etherpad, for comment JB-6. Per initial triage, it applies to original Chapters 4.
- JB-6: Public cloud uses large, xlarge (i.e. extra-large), 2xlarge as names... naming scheme here skips from large straight to 2xlarge.

Original triage notes:
- JB - Need to be more consistent in naming convention/scheme.

**Comment by CsatariGergely** [comment] 2020-05-27 13:32
The proposal in the issue is to use the AWS falvor naming what is not more logical than the scheme currently used in the RM. 
RM meeting on 2020.05.27 decided to close this issue.

**Closed by CsatariGergely** 2020-05-27 13:32 UTC
Labels: Backlog
