### ISSUE TITLE
[RA-1 RA-2] Chaining of multiple VNFs 

### ISSUE THREAD

**Issue by sukhdevkapur** [cntt-n/CNTT#1019] opened 2020-02-02 20:49 UTC
During Prague meeting, we discussed the following: 

1) OpenStack SFC API is not actively supported and may not be deployable
2) Shall we beef up work in the OpenStack Community to address this APIs? 
3) Most of the SDNs solve this and most of the operators used SDN based solutions - so, do nothing and used SDN and make SDN a part of RA1 and RA2
3) Work with OpenStack community to adopt SDN apis as neutron extension - this was considered preferred solution. Perhaps we should discuss this in the CNTT TSC

This issue applies to RA2 as well. However, NSM (Network Service Mesh) could address this in RA2. Should we consider including NSM in RA2? - Again a discussion that needs to be taken to the CNTT TSC

**Comment by fkautz** [comment] 2020-02-02 22:03
I'm happy to help advise to work out if NSM is a good fit and subsequent design decisions if such a thing is desired.

**Comment by tomkivlin** [comment] 2020-02-06 15:27
Comments from RA2 meeting 6th Feb 2020:
@ASawwaf @fkautz both made the point that NSM and service chaining needs collaboration between the workstreams. As per original comment, handle in TSC as part of wider SDN/Programmable Fabric discussions (#960, #1037).  All further discussions are part of RM Core WS.

**Comment by sukhdevkapur** [comment] 2020-04-30 22:20
We will be discussing and addressing this in the Networking Focus Group. Based upon the outcome of decision, this issue will addressed appropriately.

**Comment by pgoyal01** [comment] 2020-06-14 21:27
Closing #1080 as a duplicate of  this issue.

**Comment by pgoyal01** [comment] 2020-07-27 14:29
As moved to RM, closing this issue as per Metering of July 27, 2020.

**Closed by pgoyal01** 2020-07-27 14:29 UTC
Labels: Backlog

**Comment by ulikleber** [comment] 2020-07-28 05:54
Do we have an issue number in RM, that is used to follow up?
