### ISSUE TITLE
[RM] generic requirements of CNF in RM3.3 and RM4.1 

### ISSUE THREAD

**Issue by SaadUllahSheikh** [cntt-n/CNTT#1168] opened 2020-02-23 10:07 UTC
@tomkivlin we have some observation in RM stream . It looks the requirements are too much VNF focused and not scoped adequately for CNF .

E.g 4.1 Capabilities and Performance Measurements we can find VIM performance but not  K8S platform capabilities part 

3.3 NFVI Management Software is another example we expect something like container management as well 
Similarly for K8S at minimum performance requirements , CRD's and CRI-O etc should be included

I am sure it is included somewhere can you ignore my negligence if so and help us understand how you are tacking it .

**Comment by ASawwaf** [comment] 2020-02-23 20:55
@SaadUllahSheikh , Yes , you are right and it is on top priorities to be closed before baldy release 
@kedmison i think there is an open issue for it 


@SaadUllahSheikh we encourage you if you can contribute with some content to be reflected in RM , for 4.1 , 3.3 will be later

**Comment by tomkivlin** [comment] 2020-02-24 13:24
@SaadUllahSheikh good question, I'm not sure we've done a thorough review of it from that point of view.  We did do a PR (#621) which dealt with some of the more obvious definitions, but you're right, I think we could do with an update here.  I am not sure about adding Container Orchestration into that particular section (3.3) as containers are a software construct not an infrastructure resource however I can see it being worthwhile to update the overall definition of "NFVI Management Software" to be more agnostic to physical or virtual resources and to also update some sub-definitions, e.g.
>**Compute Resources Manager** : provides a mechanism to provision virtual resources with the help of physical compute resources

to 

>**Compute Resources Manager** : provides a mechanism to manage virtual and/or physical compute resources.

That way, the container runtime part of RA2 will more easily map to that capability, in addition to it still being applicable to a hypervisor/VIM, and also any future bare metal infrastructure manager that might be added at some point.

I think part of the problem is that some people consider Kubernetes to be part of the NFVI and others don't.  Some consider the "V" in NFVI to mean Virtual as in the same as Logical, rather than something that is virtualised.  For me, NFVI is very particular to virtualised infrastructure, as in that which is abstracted from the physical by a hypervisor.  Logical bare-metal infrastructure is not included in NFVI.  Containers are not included in NFVI (because they could be on VMs or bare metal machines).  So we either need to be super clear upfront about what we mean by Virtualised (i.e. is it something logical, or is it something running on a hypervisor) and continue to use terms like NFVI, or we need to use different terminology that is more agnostic to bare metal, virtualised and containerised workloads.

**Comment by SaadUllahSheikh** [comment] 2020-02-27 06:39
@tomkivlin you highlighted very important point actually fact is that even ETSI is not clear on it and they want to work on (GS NFV-INF 001) to have industry wide common understanding . For example in ETSI Rel-4 planning we already raised same question to NOC team.and below is abstract from WI , the fact is that there is a discussion also why say CNF because its is like Gold VNF . But having said this I only want suggest following
1. The definition is not clear and it is worthy to make this understnading clear , personally as we see all vendors , industry etc NFVI means Virtualized only . Problem is "V" when somebody defined it
2. In RM either we should make RM2 totally separate stream if not so we should at least make two sub-chapters one for NFVI and one for Containerized Infrastructure 
3. Principally this is right direction because at least for Performance benchmarks ,tests will not be same 

"The consolidation of the infrastructural aspects, by a redefinition of the NFV infrastructure (NFVI) abstraction, incorporating enhancements to support lightweight virtualization technologies (with containers as the key goal)"

obviously i am interested to give some inputs on this if we need to separate them but I think this is only best to do when at least we define exact tools and deployment models for K8S . Although @rabi-abdel  clarified this point to me before but somehow I still analyzing as following Enterprise industry models for deployments may be not most efficient way for Telco's . e.g we have following AIrship and baremetal3.io direction but infact not analyzed kubeadm etc

**Comment by CsatariGergely** [comment] 2020-02-28 08:41
I would be happy to work on this, but I would need some more clear opinions on what exactly is missing or should be changed.

I think to be able to model cloud infrastructures (or whatever definition what is okay enough for Kuberentes to admit, that it (among other things) orchestrates Linux containers (which are virtualisation infrastructure units)) in the same model we need to focus on the similarities of these in the model. Okey we call it NFVI (and maybe it is not easy to recognise, but ETSI NFV VNFC definition is about VM-s or containers (and NFVI is the thing what runs VNF-s which are a set of VNFC)) because it gives a relatively solid, box like definition of cloud infrastructure. 

If you think that RM is too VM centric in some places please list them here and let's iron those out, but let's not create a separate Kubernetes focused model.

**Comment by tomkivlin** [comment] 2020-02-28 08:56
I'm also happy to help.  My personal preference would be to remove all use of existing terms such as NFVI other than to give examples.

For example, we might use "Disaggregated network function infrastructure" or "Logical network function infrastructure" so it covers the following, showing that NFVI is the example relating to VM-based workloads.
1. VM-based, 
2. containers on bare metal, and
3. containers-on-VMs

But crucially the above examples would **not** include physical network functions (i.e. hardware-specific software/network functions).

And then the description of the "infrastructure management software" is generic to those three above scenarios - tenancy model, resource allocations, etc. - doesn't matter whether its a VM, bare metal machine or Pod Deployment, etc.

**Comment by rabi-abdel** [comment] 2020-02-28 10:04
Agree with the need to neutralise RM and make it applicable to both VMs as well as containers. I strongly agree with @CsatariGergely to **NOT** go for a completely different Model for containers or even having a different Chapter. agree with @tomkivlin to redefine the NFVI to include the above three cases.

my suggestion would be doing this in two phases:

**PHASE1**:  Create a PR to adjust the terminology and use something other than NFVI (possibly simply Cloud Infrastructure (CI) or NCI (Network Cloud Infrastructure). 

**PHASE2**: Go though the rest of the document and look at all capabilities one by one (mainly in Ch04 as @ASawwaf highlighted) and adjust/add/clarify those capabilities accordingly. I think for each capability we can either: neutralise it or clarify if applies to VMs only or Containers only. (that will address @SaadUllahSheikh concern above).

to move this forward: may I suggest @tomkivlin to have a stab at **PHASE 1** above and having all of us contributing into it?

once PHASE 1 is completed, I am hoping @CsatariGergely and @SaadUllahSheikh and @ASawwaf can help in resolving PHASE 2.

@kedmison does this work for you since this is mainly impacting RM? this work will cover  **baldy.rm.04 feature needed for Baldy**.

**Comment by ASawwaf** [comment] 2020-02-28 10:12
@rabi-abdel good approach, thx 
 I hope to catch it before baldy ,

**Comment by TFredberg** [comment] 2020-02-28 11:03
I like @rabi-abdel approach and it would likely make it slightly simpler for the networking fabric discussion within RM disussed in #1037 as well.

**Comment by tomkivlin** [comment] 2020-02-28 11:49
I'm happy to do this is the WSLs are happy with the proposal.

**Comment by rabiabdel** [comment] 2020-03-04 10:17
@kedmison are you happy with the proposed approach above?

**Comment by CsatariGergely** [comment] 2020-03-06 07:09
The approach is okay for me and I'm happy to help.

**Comment by kedmison** [comment] 2020-03-07 19:53
@tomkivlin thanks; please have a go at the Phase 1 as outlined by Rabi.

**Comment by SaadUllahSheikh** [comment] 2020-03-09 09:26
Agree totally on this .

**Comment by SaadUllahSheikh** [comment] 2020-03-09 09:38
@tomkivlin @CsatariGergely  just i have noticed this nomology should be harmonized not just for NFVI but also VIM and terms which in end user mind is strictly related to virtualization world E.g VIM terms in RM should be updated to CIM (suggestion) refer to Cloud Infra Manager . similarly for others

**Comment by tomkivlin** [comment] 2020-03-09 09:39
> @tomkivlin @CsatariGergely just i have noticed this nomology should be harmonized not just for NFVI but also VIM and terms which in end user mind is strictly related to virtualization world E.g VIM terms in RM should be updated to CIM (suggestion) refer to Cloud Infra Manager . similarly for others

Yes agree - I am preparing a PR now, hopefully get it ready for review today.

**Comment by markshostak** [comment] 2020-03-10 09:34
@tomkivlin, @SaadUllahSheikh and @rabi-abdel One comment: While the RM was always intended to be made agnostic to VM and container, the document will be more easily understood by people experienced in cloud, yet not familiar w/ CNTT, if we don't make up new generic names for functions people are already familiar with. For example, instead of making up CIM, use "VIM _or equivalent_". Then it's obvious what you mean, without a trip to to the glossary, diagram, etc.

**Comment by ulikleber** [comment] 2020-03-19 13:01
If we want to be agnostic, that means, that our term for infrastructure needs to cover both, VMs and Containers, and our term for the infrastructure's manager also needs to be independent. This was the intend in ETSI from the beginning. Containerization is a Virtualization technology.
If we now splite between VIM and CIM, we work in the opposite direction than what we want to achieve. VIM and CIM will be very much aware of their capability to support only one technology.
Being agnostic means that one term covers both.

**Closed** 2020-04-03 10:10 UTC
