### ISSUE TITLE
[RM Appendix-A] [Clarifying Transitional Plan for VNF Design]

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#678] opened 2019-11-22 10:44 UTC
As per comments made on  https://github.com/cntt-n/CNTT/pull/653 to include @xavier-grall concern regarding SR-IOV.

**Comment by markshostak** [comment] 2019-11-27 06:03
Xavier, You've done a lot of work on this, so I'm thinking you can reuse it here. If you like, I can tag team this one with you. Just let me know. Thanks, -Mark

**Comment by pgoyal01** [comment] 2020-07-28 15:39
@ASawwaf @walterkozlowski should this be closed as it is not clear as to what the issue is

**Comment by walterkozlowski** [comment] 2020-07-29 02:31
Closing issue due to lack of description what the issue is about.

**Closed** 2020-07-29 02:31 UTC
