### ISSUE TITLE
[RA1 ch03 & ch04] Support of Service Function Chaining to be developped

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#1055] opened 2020-02-11 16:50 UTC
Refers to Chapter 2 requirement 'req.inf.ntw.04':
' The Architecture should support service function chaining'

**Comment by pgoyal01** [comment] 2020-02-11 20:23
@karinesevilla duplicate of Issue #1019

**Comment by pgoyal01** [comment] 2020-05-11 14:37
Closing as duplicate of Issue #1080

**Closed by pgoyal01** 2020-05-11 14:37 UTC
Labels: Backlog
