### ISSUE TITLE
[RC1 Ch04] Define the test cases for exposed infrastructure capabilities

### ISSUE THREAD

**Issue by deebhatia** [cntt-n/CNTT#774] opened 2019-12-09 13:34 UTC
This issue is to capture the tests the exposed infrastructure capabilities as defined in [RM §4.1.2](https://cntt-n.github.io/CNTT/doc/ref_model/chapters/chapter04.html#4.1.2).

**Comment by mf4716** [comment] 2019-12-13 05:53
Ch 4 authors, can we get an update?

Ch04: NFVI TC Traceability to RA Requirements: Rajesh, Dan, Ashok,Deepanshu (confirmed)

**Comment by mf4716** [comment] 2019-12-17 04:55
@deebhatia , @xudan16 , @ASawwaf , @rrajesh70 - hi, can we get an update please?

**Comment by mf4716** [comment] 2019-12-19 23:25
status?

**Comment by mf4716** [comment] 2019-12-26 21:15
@deebhatia - status?

**Comment by mf4716** [comment] 2020-01-08 02:46
@deebhatia - status?

**Comment by mf4716** [comment] 2020-03-04 02:27
status @deebhatia ?

**Comment by fuqiao123** [comment] 2020-03-30 09:15
Does this issue mean we should also add the requirement in RM chp4 into the test case consideration? Can this covered by requirement in RA chp 05？

**Comment by fuqiao123** [comment] 2020-04-01 03:11
No status for this one for a while. I would have the team review this one on Apr. 1st RC call and see if we should drop it.

**Comment by fuqiao123** [comment] 2020-04-01 13:22
close this since no PR created and no contributors

**Closed by fuqiao123** 2020-04-01 13:22 UTC
