### ISSUE TITLE
[RC1 Dev] Write 4.3.4.1 Identity - Keystone

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#830] opened 2019-12-23 09:51 UTC
It will simply detail the testcases already executed in NFVI API Compliance
https://lists.opnfv.org/g/opnfv-tsc/message/5717

**Comment by deebhatia** [comment] 2019-12-23 10:02
@collivier It is a duplicate of #808 . I was thinking of something like this:

| Test case # | sub-category | Description | Requirement # |
|----|------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `cert.api.identity.01` | API Discovery | Test that user is able to list api versions. |  |
| `cert.api.identity.01` | API Discovery | Test that user is able to list api media types. |  |
| `cert.api.identity.01` | API Discovery | Test that user is able to list api version statuses. |  |
| `cert.api.identity.01` | API Discovery | Test that user is able to see v3 as current in listed api versions. |  |
| `cert.api.identity.01` | Token | Test that user is able to create an authentication token. |  |
| `cert.api.identity.01` | Token | Test that user is able to validate an existing authentication token. |  |
| `cert.api.identity.01` | Application Credential | Test that user is able to list active application credentials. |  |
| `cert.api.identity.01` | Application Credential | Test that user is able to create an application credential with expiry time. |  |
| `cert.api.identity.01` | Application Credential | Test that user is able to delete an existing application credential. |  |
| `cert.api.identity.01` | Application Credential | Test that user is able to authenticate an existing application credential. |  |
| `cert.api.identity.01` | Application Credential | Test that admin user is able to create an application credential with roles. |  |
| `cert.api.identity.01` | Service | Test that user is able to list service catalog and it contains endpoint for each core service. | `req.int.api.01` |
| `cert.api.identity.01` | Service | Test that admin user is able to list service catalog and it contains endpoint for each all available services. | `req.int.api.01` |
| `cert.api.identity.01` | Service | Test that admin user is able to create a new endpoint. |  |
| `cert.api.identity.01` | Service | Test that admin user is able to update an existing endpoint. |  |
| `cert.api.identity.01` | Service | Test that admin user is able to delete an existing endpoint. |  |
| `cert.api.identity.01` | Service | Test that admin user is able to create a service. |  |
| `cert.api.identity.01` | Service | Test that admin user is able to update an existing service. |  |
| `cert.api.identity.01` | Service | Test that admin user is able to delete an existing service. |  |
| `cert.api.identity.01` | Security Compliance | Test that user account gets locked out for a particular duration after a defined number of incorrect attempts. |  |
| `cert.api.identity.01` | Domain | Test that user is able to check default domain. |  |
| `cert.api.identity.01` | Domain | Test that admin user is able to list existing domains. |  |
| `cert.api.identity.01` | Domain | Test that admin user is able to create a domain. |  |
| `cert.api.identity.01` | Domain | Test that admin user is able to enable/disable a domain. |  |
| `cert.api.identity.01` | Domain | Test that admin user is able to delete a domain. |  |
| `cert.api.identity.01` | Tenant | Test that user is able to list accessible tenants. |  |
| `cert.api.identity.01` | Tenant | Test that admin user is able to create a tenant. |  |
| `cert.api.identity.01` | Tenant | Test that admin user is able to update an existing tenant. |  |
| `cert.api.identity.01` | Tenant | Test that admin user is able to delete an existing tenant. |  |
| `cert.api.identity.01` | User | Test that user is able to update his/her own password. |  |
| `cert.api.identity.01` | User | Test that admin user is able to list existing users. |  |
| `cert.api.identity.01` | User | Test that admin user is able to create a user. |  |
| `cert.api.identity.01` | User | Test that admin user is able to update an existing user details. |  |
| `cert.api.identity.01` | User | Test that admin user is able to delete an existing user. |  |
| `cert.api.identity.01` | User | Test that admin user is able to add user to an existing tenant. |  |
| `cert.api.identity.01` | User | Test that admin user is able to remove user from an existing tenant. |  |
| `cert.api.identity.01` | User | Test that admin user is able to list all tenants associated with an existing user. |  |
| `cert.api.identity.01` | Region | Test that admin user is able to list regions. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to list roles. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to create a role. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to delete a role. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to list the roles of the user. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to assign a role to the user. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to revoke a role to the user. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to list the roles of the group. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to assign a role to the group. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to revoke a role to the group. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to create a domain role. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to delete a domain role. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to list the roles of the domain user. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to assign a role to the domain user. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to revoke a role to the domain user. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to list the roles of the domain group. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to assign a role to the domain group. |  |
| `cert.api.identity.01` | Role | Test that admin user is able to revoke a role to the domain group. |  |

**Comment by collivier** [comment] 2019-12-23 11:28
@deebhatia I think it's more or less the opposite: you're mostly duplicating the upstream work and listing the ~2000 tests already executed in Functest CNTT costs lots of time for a duplication in the best cases. 
See opnfv/functest-smoke-cntt:hunter in https://build.opnfv.org/ci/view/functest/job/functest-hunter-daily/373/

**Comment by deebhatia** [comment] 2019-12-23 11:38
@collivier Yes. Initially, it is duplication. However, RC should contain a self sustained list of test scenarios eventually if not in Snezka so that it can push those in upstream if missing there. That's why we have separate chapters: Ch04 to document test cases and Ch09 to map them into test frameworks. IMO, what your change currently addresses is essentially the content of Ch09. Opinion?

**Comment by collivier** [comment] 2019-12-23 11:44
@deebhatia you may be highlighting that we should change the overall design. If we continue the current design, we will simply map in Ch09 the functest-smoke-cntt testcase names.
The proposal here is straightforward regarding RA1 Chapter 5 (API) and then I don't see the point to add an abstract requirements which can't me mapped neither with API and opensource testcases.

**Comment by deebhatia** [comment] 2019-12-23 12:03
Yes, you can say that. My argument is that if we do it like the current approach, we give the ownership to framework repos to control CNTT test scenarios. If that is the agreed design, I am **okay** as far as we can track what additional test cases we want (if there is any) and still not part of open source test frameworks. I understand it is a more probable scenario in NFVI tests rather than API tests (as it is mostly covered by tempest/rally).

**Comment by collivier** [comment] 2019-12-23 12:11
@deebhatia Not at all. The proposal here selects the upstream tests according to the API described in RA1 Chapter 5. Functest here already conforms with CNTT API which may be misleading you. If API changes, any CNTT member is free to contribute to Functest to update the testcase rules. Else I don't see the point about adding new testcases as it's out of this proposal.

**Comment by deebhatia** [comment] 2019-12-23 12:21
Okay. Understood.

**Comment by collivier** [comment] 2019-12-23 12:28
@deebhatia Thank you for your feedbacks.
I'm finishing Nova and Neutron in the same way then I will complete Ch09.
I put as highest priorities, to detail the test framework and methodology highlighting the capabilities to add new testcases right after.

**Closed** 2019-12-30 14:53 UTC
Labels: RC 1 Dev, RC 1 NFVI
